DROP TABLE IF EXISTS CONCERT;
DROP TABLE IF EXISTS PERFORMER;
CREATE TABLE CONCERT(
ID              LONG PRIMARY KEY AUTO_INCREMENT,
TITLE           VARCHAR(255),
DATE            TIMESTAMP,
PERFORMER_ID    LONG);

CREATE TABLE PERFORMER(
ID       LONG PRIMARY KEY AUTO_INCREMENT,
NAME     VARCHAR(255),
IMAGEURI VARCHAR(255),
GENRE    VARCHAR(30));

ALTER TABLE CONCERT ADD FOREIGN KEY (PERFORMER_ID) REFERENCES PERFORMER(ID);